# Generated by Django 5.0.1 on 2024-01-23 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portfolo_app.basemodel')),
                ('about_info', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('name_custom', models.CharField(max_length=255)),
                ('birthday', models.DateField()),
                ('website', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('city', models.TextField(max_length=255)),
                ('age', models.SmallIntegerField()),
                ('degree', models.TextField(max_length=255)),
                ('phemailone', models.EmailField(max_length=254)),
                ('freelance', models.TextField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
            bases=('portfolo_app.basemodel',),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portfolo_app.basemodel')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
            ],
            bases=('portfolo_app.basemodel',),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portfolo_app.basemodel')),
                ('location', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('call', models.IntegerField()),
            ],
            bases=('portfolo_app.basemodel',),
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portfolo_app.basemodel')),
                ('title', models.CharField(max_length=255)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('where_he_studied', models.CharField(max_length=255)),
                ('text', models.TextField()),
            ],
            bases=('portfolo_app.basemodel',),
        ),
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portfolo_app.basemodel')),
                ('name', models.CharField(max_length=255)),
                ('title', models.TextField()),
                ('img', models.ImageField(upload_to='')),
                ('number', models.IntegerField()),
            ],
            bases=('portfolo_app.basemodel',),
        ),
        migrations.CreateModel(
            name='ProfessionalExperience',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portfolo_app.basemodel')),
                ('title', models.CharField(max_length=255)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('where_it_works', models.CharField(max_length=255)),
                ('text', models.TextField()),
            ],
            bases=('portfolo_app.basemodel',),
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portfolo_app.basemodel')),
                ('name', models.TextField(max_length=255)),
                ('percent', models.SmallIntegerField()),
            ],
            bases=('portfolo_app.basemodel',),
        ),
        migrations.CreateModel(
            name='Sumary',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portfolo_app.basemodel')),
                ('name', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
            bases=('portfolo_app.basemodel',),
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portfolo_app.basemodel')),
                ('name', models.CharField(max_length=255)),
                ('job', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='')),
                ('text', models.TextField()),
            ],
            bases=('portfolo_app.basemodel',),
        ),
        migrations.CreateModel(
            name='TypeService',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portfolo_app.basemodel')),
                ('type_title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('img', models.ImageField(upload_to='')),
            ],
            bases=('portfolo_app.basemodel',),
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portfolo_app.basemodel')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='portfolio')),
                ('text', models.CharField(max_length=255)),
                ('data', models.DateTimeField()),
                ('url', models.URLField()),
                ('status', models.BooleanField(default=True)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='portfolo_app.category')),
            ],
            bases=('portfolo_app.basemodel',),
        ),
    ]
