# Generated by Django 5.0.1 on 2024-01-23 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typeservice',
            old_name='type_title',
            new_name='title',
        ),
    ]
