# Generated by Django 5.0.1 on 2024-01-24 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolo_app', '0002_rename_type_title_typeservice_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portfolo_app.basemodel')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='')),
            ],
            bases=('portfolo_app.basemodel',),
        ),
    ]
