# Generated by Django 5.0.1 on 2024-01-26 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolo_app', '0003_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fact',
            name='img',
            field=models.CharField(choices=[('bi bi-emoji-smile', 'Happy Clients'), ('bi bi-journal-richtext', 'Projects'), ('bi bi-headset', 'Hours Of Support'), ('bi bi-people', 'Hard Workers')], max_length=255),
        ),
        migrations.AlterField(
            model_name='home',
            name='img',
            field=models.ImageField(upload_to='static/assets/img/portfolio'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(upload_to='static/assets/img/portfolio'),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='img',
            field=models.ImageField(upload_to='static/assets/img'),
        ),
        migrations.AlterField(
            model_name='typeservice',
            name='img',
            field=models.ImageField(upload_to='static/assets/img/portfolio'),
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portfolo_app.basemodel')),
                ('img', models.ImageField(upload_to='static/assets/img/portfolio')),
                ('portfolio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolo_app.portfolio')),
            ],
            bases=('portfolo_app.basemodel',),
        ),
    ]
