# Generated by Django 5.0.1 on 2024-01-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolo_app', '0004_alter_fact_img_alter_home_img_alter_portfolio_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='end_year',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='professionalexperience',
            name='end_year',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
