# Generated by Django 5.0.1 on 2024-01-31 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolo_app', '0005_alter_education_end_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='name',
            field=models.TextField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='typeservice',
            name='img',
            field=models.CharField(choices=[('col-lg-4 col-md-6 icon-box', 'Lorem Ipsum'), ('bi bi-journal-richtext', 'Projects'), ('bi bi-headset', 'Hours Of Support'), ('bi bi-people', 'Hard Workers')], max_length=255),
        ),
    ]
