# Generated by Django 5.0.1 on 2024-01-31 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolo_app', '0006_alter_skills_name_alter_typeservice_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
