# Generated by Django 5.0.1 on 2024-01-31 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolo_app', '0007_contact_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='call',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='img',
            field=models.CharField(choices=[('bx bxs-quote-alt-left quote-icon-left', 'bog'), ('col-lg-4 col-md-6 icon-box', 'pitichka'), ('col-lg-4 col-md-6 icon-box', 'antina'), ('col-lg-4 col-md-6 icon-box', 'durben'), ('col-lg-4 col-md-6 icon-box', 'quyosh'), ('col-lg-4 col-md-6 icon-box', 'kalindar')], max_length=255),
        ),
    ]
