# Generated by Django 5.0.1 on 2024-01-31 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolo_app', '0009_alter_testimonials_img_alter_typeservice_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeservice',
            name='img',
            field=models.CharField(choices=[('col-lg-4 col-md-6 icon-box', 'Lorem Ipsum'), ('bi bi-card-checklist', 'pitichka'), ('bi bi-bar-chart', 'antina'), ('bi bi-binoculars', 'durben'), ('bi bi-brightness-high', 'quyosh'), ('bi bi-calendar4-week', 'kalindar')], max_length=255),
        ),
    ]
