# Generated by Django 5.0.1 on 2024-01-31 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolo_app', '0010_alter_typeservice_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioimage',
            name='portfolio_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolo_app.portfolio'),
        ),
        migrations.AlterField(
            model_name='typeservice',
            name='img',
            field=models.CharField(choices=[('bi bi-briefcase', 'Lorem Ipsum'), ('bi bi-card-checklist', 'pitichka'), ('bi bi-bar-chart', 'antina'), ('bi bi-binoculars', 'durben'), ('bi bi-brightness-high', 'quyosh'), ('bi bi-calendar4-week', 'kalindar')], max_length=255),
        ),
    ]
